### ISSUE TITLE
Under build-and-publish så caches ikke maven avhengigheter

### ISSUE THREAD

**Issue by joakibj** [navikt/dok-workflows#1]
Når setup-java forsøker å hente cache `'maven'` så finner den ingenting pga det ikke er noe step som lagrer til cache

**Comment by avoldsund** [comment]
Ref. https://nav-it.slack.com/archives/C60FFACN5/p1663858322225999 skal maven-cachinga fungere slik oppsettet er no, med den svakheita at alle endringar i pom-fila vil trigge nedlasting av alle dependencies på nytt.

**Comment by joakibj** [comment]
Foreslår å hente opp cache basert på ukenr og rotere på det

**Comment by joakibj** [comment]
Setter opp cache basert på ukenummer. GHA cache er branch lokal så vi kan ikke få alt til å gå fort
