### ISSUE TITLE
Draft release før deploy til dev miljø i main flowen

### ISSUE THREAD

**Issue by joakibj** [navikt/dok-workflows#4]
Noen ganger ønsker vi å prodsette så raskt som mulig

Foreslår å flytte draft release til rett etter bygg i `build-deploy-main.yml` flowen
@avoldsund

**Comment by avoldsund** [comment]
Jepp. Høyrast bra ut 👍

**Comment by avoldsund** [comment]
Dette blei med i https://github.com/navikt/dok-workflows/pull/5 👍
